version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: nextjs_dashboard_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: nextjs_dashboard
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nextjs_dashboard_phpmyadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin123
    networks:
      - mysql_network
    depends_on:
      - db

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_data:
